(function(){
  async function api(url,options={}){const r=await fetch(url,{credentials:'same-origin',headers:{'Content-Type':'application/json',...(options.headers||{})},...options});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Não foi possível concluir.');return d}
  const $=s=>document.querySelector(s);
  function err(el,e){if(el)el.textContent=e.message||String(e)}
  function escape(v){return String(v||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
  async function initLogin(){const d=await api('/api/admin/me');if(d.authenticated){location.href='admin.html';return}if(d.setupRequired){$('#setupNotice').style.display='block';$('#setupLink').style.display='inline'}$('#adminLoginForm').onsubmit=async e=>{e.preventDefault();$('#adminError').textContent='';try{const f=e.target;await api('/api/admin/login',{method:'POST',body:JSON.stringify({email:f.email.value,password:f.password.value})});location.href='admin.html'}catch(ex){err($('#adminError'),ex)}}}
  async function initSetup(){const d=await api('/api/admin/setup/status');if(!d.setupRequired){location.href='admin-login.html';return}$('#adminSetupForm').onsubmit=async e=>{e.preventDefault();$('#setupError').textContent='';const f=e.target;if(f.password.value!==f.confirmPassword.value){$('#setupError').textContent='As senhas não coincidem.';return}try{await api('/api/admin/setup',{method:'POST',body:JSON.stringify({setupKey:f.setupKey.value,name:f.name.value,email:f.email.value,password:f.password.value})});location.href='admin-login.html'}catch(ex){err($('#setupError'),ex)}}}
  function renderFactors(factors){
    const el=$('#factorList');if(!el)return;
    const names={plastico:'Plástico',papel:'Papel',vidro:'Vidro',metal:'Metal',outro:'Outro'};
    el.innerHTML=Object.keys(names).map(k=>{const f=factors[k];return `<div class="admin-row"><div class="admin-row-main"><strong>${names[k]}</strong><small>${f?`${Number(f.pointsPerKg||0).toLocaleString('pt-BR')} pts/kg · CO₂ ${Number(f.co2PerKg||0).toLocaleString('pt-BR')} kg/kg · água ${f.waterPerKg==null?'não estimada':Number(f.waterPerKg||0).toLocaleString('pt-BR')+' L/kg'} · energia ${f.energyPerKg==null?'não estimada':Number(f.energyPerKg||0).toLocaleString('pt-BR')+' kWh/kg'}`:'Ainda não configurado'}</small><small>${f?'Fonte: '+escape(f.source):'Sem fator cadastrado. Produtos desse material podem ser salvos pelos usuários, mas não registrados até a configuração.'}</small></div><div class="admin-row-actions"><button data-edit-factor="${k}">Editar</button></div></div>`}).join('');
    el.querySelectorAll('[data-edit-factor]').forEach(b=>b.onclick=()=>{const k=b.dataset.editFactor,f=factors[k],form=$('#factorForm');form.material.value=k;form.pointsPerKg.value=f?.pointsPerKg??'';form.co2PerKg.value=f?.co2PerKg??'';form.waterPerKg.value=f?.waterPerKg??'';form.treePerKg.value=f?.treePerKg??'';form.energyPerKg.value=f?.energyPerKg??'';form.source.value=f?.source??'';window.scrollTo({top:form.offsetTop-20,behavior:'smooth'})});
  }
  function renderPartnerSelect(ps){const el=$('#couponPartner');if(el)el.innerHTML='<option value="">Selecione...</option>'+ps.map(p=>`<option value="${p.id}">${escape(p.name)}</option>`).join('')}
  function renderPartners(ps){const el=$('#partnerList');if(!el)return;el.innerHTML=ps.length?ps.map(p=>`<div class="admin-row"><div class="admin-row-main"><strong>${escape(p.name)}</strong><small>${escape(p.category)} · ${escape(p.description||'Sem descrição')}</small></div><div class="admin-row-actions"><button data-edit-partner="${p.id}">Editar</button><button class="delete" data-delete-partner="${p.id}">Excluir</button></div></div>`).join(''):'<div class="admin-empty">Nenhum parceiro cadastrado.</div>';el.querySelectorAll('[data-delete-partner]').forEach(b=>b.onclick=async()=>{if(!confirm('Excluir este parceiro e as ofertas vinculadas?'))return;await api('/api/admin/partners/'+b.dataset.deletePartner,{method:'DELETE'});location.reload()});el.querySelectorAll('[data-edit-partner]').forEach(b=>b.onclick=()=>{const p=ps.find(x=>x.id===b.dataset.editPartner),f=$('#partnerForm');f.dataset.edit=p.id;f.name.value=p.name;f.category.value=p.category;f.description.value=p.description||'';f.benefit.value=p.benefit||'';f.website.value=p.website||'';$('#partnerSubmit').textContent='Salvar parceiro';window.scrollTo({top:f.offsetTop-20,behavior:'smooth'})})}
  function renderCoupons(cs){const el=$('#couponList');if(!el)return;el.innerHTML=cs.length?cs.map(c=>`<div class="admin-row"><div class="admin-row-main"><strong>${escape(c.title)} — ${escape(c.partner||'')}</strong><small>${escape(c.discount)} · código ${escape(c.code||'não definido')} · ${Number(c.pointsCost||0).toLocaleString('pt-BR')} pontos · ${c.validUntil?'até '+new Date(c.validUntil).toLocaleDateString('pt-BR'):'sem validade definida'}</small></div><div class="admin-row-actions"><button data-edit-coupon="${c.id}">Editar</button><button class="delete" data-delete-coupon="${c.id}">Excluir</button></div></div>`).join(''):'<div class="admin-empty">Nenhum cupom cadastrado.</div>';el.querySelectorAll('[data-delete-coupon]').forEach(b=>b.onclick=async()=>{if(!confirm('Excluir este cupom?'))return;await api('/api/admin/coupons/'+b.dataset.deleteCoupon,{method:'DELETE'});location.reload()});el.querySelectorAll('[data-edit-coupon]').forEach(b=>b.onclick=()=>{const c=cs.find(x=>x.id===b.dataset.editCoupon),f=$('#couponForm');f.dataset.edit=c.id;f.partnerId.value=c.partnerId;f.title.value=c.title;f.discount.value=c.discount;f.code.value=c.code||'';f.description.value=c.description;f.pointsCost.value=c.pointsCost;f.validUntil.value=c.validUntil?c.validUntil.slice(0,10):'';$('#couponSubmit').textContent='Salvar cupom';window.scrollTo({top:f.offsetTop-20,behavior:'smooth'})})}
  function bindForms(){
    const pf=$('#partnerForm');if(pf){pf.onsubmit=async e=>{e.preventDefault();const data={name:pf.name.value,category:pf.category.value,description:pf.description.value,benefit:pf.benefit.value,website:pf.website.value};try{if(pf.dataset.edit)await api('/api/admin/partners/'+pf.dataset.edit,{method:'PATCH',body:JSON.stringify(data)});else await api('/api/admin/partners',{method:'POST',body:JSON.stringify(data)});location.reload()}catch(ex){alert(ex.message)}};$('#partnerCancel').onclick=()=>{pf.reset();delete pf.dataset.edit;$('#partnerSubmit').textContent='Cadastrar parceiro'}}
    const cf=$('#couponForm');if(cf){cf.onsubmit=async e=>{e.preventDefault();const data={partnerId:cf.partnerId.value,title:cf.title.value,discount:cf.discount.value,code:cf.code.value.trim(),description:cf.description.value,pointsCost:Number(cf.pointsCost.value),validUntil:cf.validUntil.value||null};try{if(cf.dataset.edit)await api('/api/admin/coupons/'+cf.dataset.edit,{method:'PATCH',body:JSON.stringify(data)});else await api('/api/admin/coupons',{method:'POST',body:JSON.stringify(data)});location.reload()}catch(ex){alert(ex.message)}};$('#couponCancel').onclick=()=>{cf.reset();delete cf.dataset.edit;$('#couponSubmit').textContent='Cadastrar cupom'}}
    const ff=$('#factorForm');if(ff){ff.onsubmit=async e=>{e.preventDefault();const data={material:ff.material.value,pointsPerKg:Number(ff.pointsPerKg.value),co2PerKg:Number(ff.co2PerKg.value),waterPerKg:Number(ff.waterPerKg.value),treePerKg:ff.treePerKg.value===''?null:Number(ff.treePerKg.value),energyPerKg:ff.energyPerKg.value===''?null:Number(ff.energyPerKg.value),source:ff.source.value.trim()};try{await api('/api/admin/material-factors',{method:'PUT',body:JSON.stringify(data)});location.reload()}catch(ex){alert(ex.message)}};$('#factorCancel').onclick=()=>ff.reset()}
  }
  async function initDashboard(){const me=await api('/api/admin/me');if(!me.authenticated){location.href='admin-login.html';return}$('#adminName').textContent=me.admin.name;const d=await api('/api/admin/dashboard');const s=d.stats;for(const [k,v] of Object.entries({users:s.users,scans:s.scans,pointsIssued:s.pointsIssued,pointsSpent:s.pointsSpent,redemptions:s.redemptions,partners:s.partners,activeCoupons:s.activeCoupons,usersWithAddress:s.usersWithAddress,configuredProducts:s.configuredProducts})) { const node=document.querySelector(`[data-stat="${k}"]`); if(node) node.textContent=Number(v||0).toLocaleString('pt-BR'); }const factors=await api('/api/admin/material-factors');renderFactors(factors.factors);const partners=await api('/api/admin/partners');renderPartners(partners.partners);const coupons=await api('/api/admin/coupons');renderPartnerSelect(coupons.partners);renderCoupons(coupons.coupons);bindForms();$('#logout').onclick=async()=>{await api('/api/admin/logout',{method:'POST'});location.href='admin-login.html'}}
  document.addEventListener('DOMContentLoaded',()=>{if(document.getElementById('adminLoginForm'))initLogin();if(document.getElementById('adminSetupForm'))initSetup();if(document.getElementById('adminDashboard'))initDashboard().catch(e=>{alert(e.message);location.href='admin-login.html'})});
})();
